import { open, sleep, shot } from './lib.mjs';
const { browser, page, logs } = await open({ width: 1280, height: 800 });
await sleep(1500);
await shot(page, 'brand_menu');
await page.click('#playAI', { force: true });
await sleep(2200);
await shot(page, 'brand_game');
await page.evaluate(() => window.__game.force([4]));
await page.keyboard.press('Space');
await sleep(7000);
await shot(page, 'brand_bridge');
const m = await open({ width: 390, height: 844, mobile: true });
await sleep(1500);
await shot(m.page, 'brand_menu_phone');
await m.page.tap('#playAI', { force: true });
await sleep(2000);
await shot(m.page, 'brand_game_phone');
console.log([...logs, ...m.logs].join('\n') || 'console clean');
await m.browser.close();
await browser.close();
